-- karthik_workspace | EMP_001 | [v1.0][untagged] 2026-08-29 08:29 | ALL | main

MERGE INTO demo_catalog.admin.data_flow_control_header AS tgt
USING (SELECT 'EMP_001' AS DATA_FLOW_GROUP_ID,'JOB' AS TRIGGER_TYPE,'L0' AS ETL_LAYER,'Y' AS IS_ACTIVE,current_timestamp() AS INSERTED_TS,current_timestamp() AS UPDATED_TS) AS src
ON tgt.DATA_FLOW_GROUP_ID=src.DATA_FLOW_GROUP_ID AND tgt.ETL_LAYER=src.ETL_LAYER
WHEN MATCHED THEN UPDATE SET tgt.TRIGGER_TYPE=src.TRIGGER_TYPE,tgt.IS_ACTIVE=src.IS_ACTIVE,tgt.UPDATED_TS=src.UPDATED_TS
WHEN NOT MATCHED THEN INSERT *;

MERGE INTO demo_catalog.admin.data_flow_l0_detail AS tgt
USING (SELECT 'EMP_001' AS DATA_FLOW_GROUP_ID,'https://raw.githubusercontent.com/ID-KARTHIKEYAN/DATA_INTEGRATION/main/employee_master_data_messy_10000.csv' AS SOURCE,'employee_master_data_messy_10000.csv' AS SOURCE_OBJ_NAME,'csv' AS INPUT_FILE_FORMAT,'https://raw.githubusercontent.com/ID-KARTHIKEYAN/DATA_INTEGRATION/refs/heads/main' AS STORAGE_TYPE,'FULL' AS LOAD_TYPE,'Y' AS IS_ACTIVE,current_timestamp() AS INSERTED_TS,current_timestamp() AS UPDATED_TS) AS src
ON tgt.DATA_FLOW_GROUP_ID=src.DATA_FLOW_GROUP_ID AND tgt.SOURCE_OBJ_NAME=src.SOURCE_OBJ_NAME
WHEN MATCHED THEN UPDATE SET tgt.SOURCE=src.SOURCE,tgt.INPUT_FILE_FORMAT=src.INPUT_FILE_FORMAT,tgt.STORAGE_TYPE=src.STORAGE_TYPE,tgt.LOAD_TYPE=src.LOAD_TYPE,tgt.IS_ACTIVE=src.IS_ACTIVE,tgt.UPDATED_TS=src.UPDATED_TS
WHEN NOT MATCHED THEN INSERT *;
