-- karthik_workspace | EMPLOYEE_MASTER_L0 | [v1.0][untagged] 2026-10-02 07:08 | L0 | main

MERGE INTO demo_catalog.admin.data_flow_control_header AS tgt
USING (SELECT 'EMPLOYEE_MASTER_L0' AS DATA_FLOW_GROUP_ID,'DLT' AS TRIGGER_TYPE,'L0' AS ETL_LAYER,'Y' AS IS_ACTIVE,current_timestamp() AS INSERTED_TS,current_timestamp() AS UPDATED_TS) AS src
ON tgt.DATA_FLOW_GROUP_ID=src.DATA_FLOW_GROUP_ID AND tgt.ETL_LAYER=src.ETL_LAYER
WHEN MATCHED THEN UPDATE SET tgt.TRIGGER_TYPE=src.TRIGGER_TYPE,tgt.IS_ACTIVE=src.IS_ACTIVE,tgt.UPDATED_TS=src.UPDATED_TS
WHEN NOT MATCHED THEN INSERT *;

MERGE INTO demo_catalog.admin.data_flow_l0_detail AS tgt
USING (SELECT 'EMPLOYEE_MASTER_L0' AS DATA_FLOW_GROUP_ID,'' AS SOURCE,'employees' AS SOURCE_OBJ_NAME,'csv' AS INPUT_FILE_FORMAT,'GITHUB' AS STORAGE_TYPE,'FULL' AS LOAD_TYPE,'Y' AS IS_ACTIVE,current_timestamp() AS INSERTED_TS,current_timestamp() AS UPDATED_TS) AS src
ON tgt.DATA_FLOW_GROUP_ID=src.DATA_FLOW_GROUP_ID AND tgt.SOURCE_OBJ_NAME=src.SOURCE_OBJ_NAME
WHEN MATCHED THEN UPDATE SET tgt.SOURCE=src.SOURCE,tgt.INPUT_FILE_FORMAT=src.INPUT_FILE_FORMAT,tgt.STORAGE_TYPE=src.STORAGE_TYPE,tgt.LOAD_TYPE=src.LOAD_TYPE,tgt.IS_ACTIVE=src.IS_ACTIVE,tgt.UPDATED_TS=src.UPDATED_TS
WHEN NOT MATCHED THEN INSERT *;
